### ISSUE TITLE
Issue on build.

### ISSUE THREAD

**Issue by vladbondarenko** [ykzts/webp-proxy#62]
# go get -u github.com/ykzts/webp-proxy
# github.com/harukasan/go-libwebp/webp
go/src/github.com/harukasan/go-libwebp/webp/decode.go:5:10: fatal error: webp/decode.h: No such file or directory
 #include <webp/decode.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
# github.com/pixiv/go-libjpeg/jpeg
go/src/github.com/pixiv/go-libjpeg/jpeg/compress.go:6:10: fatal error: jpeglib.h: No such file or directory
 #include "jpeglib.h"
          ^~~~~~~~~~~
compilation terminated.

**Comment by ykzts** [comment]
```console
$ sudo apt-get install libjpeg-dev libwebp-dev
```

or

```console
$ sudo yum install libjpeg-dev libwebp-dev
```

**Comment by vladbondarenko** [comment]
[root@ip-172-31-35-97 ~]# go get -u github.com/ykzts/webp-proxy
# github.com/harukasan/go-libwebp/webp
go/src/github.com/harukasan/go-libwebp/webp/decode.go:68: cf.format undefined (type C.struct_WebPBitstreamFeatures has no field or method format)
go/src/github.com/harukasan/go-libwebp/webp/decode.go:219: config.options.dithering_strength undefined (type C.struct_WebPDecoderOptions has no field or method dithering_strength)
[root@ip-172-31-35-97 ~]#

**Comment by ykzts** [comment]
GitHub is not StackOverflow.
